// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      http://csharpindepth.com/articles/general/singleton.aspx
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace com.henrick.games.maze {
	{
		public sealed class SingletonExample
		{
			private SingletonExample() {}

			public static SingletonExample Instance { get { return Nested.instance; } }

			private class Nested {
				static Nested() {

				}

				internal static readonly SingletonExample instance = new SingletonExample ();
			}
		}
	}
}

